export { ReactComponent as BitcoinIcon}	 from "./bitcoin.svg"
export { ReactComponent as SolanaIcon} 	 from "./solana.svg"
export { ReactComponent as EthereumIcon} from "./ethereum.svg"
export { ReactComponent as BinanceIcon}  from "./binance.svg"
export { ReactComponent as ShibaInuIcon} from "./shibainu.svg"
